const board_leader = [
    {
      id: 1,
      name: "MR. N. CHANDRASEKARAN",
      designation: "Chairman",
      img: "/108.webp",
      text: "Mr. N. Chandrasekaran serves as Chairman of the board of Tata Sons, the holding company and promoter of more than 100 Tata operating companies with aggregate annual revenues of more than US $150 billion. He joined the board of Tata Sons in October 2016 and was appointed Chairman in January 2017. His appointment as Chairman of Tata Sons followed a 30-year career at Tata Consulting Services. Mr. Chandrasekaran rose through the ranks to become the CEO and under his leadership, TCS consolidated its position as the largest private sector employer in India and India's most valuable company. Since he has taken over as Chairman of Tata Sons, Mr. Chandrasekaran has been driving transformation of the group towards digital, sustainability and supply chain resilience. The group has forayed into new businesses including electronics manufacturing, semiconductor, EV battery manufacturing, consumer internet platform, and mobile technology for 5G. The Tata group has expanded its aviation presence with the acquisition of Air India and is building a large global airline. Mr. Chandrasekaran was conferred with the Padma Bhushan, one of the highest civilian awards in India, in the field of trade and industry in 2022. The French Government conferred him with Légion d'Honneur, the highest civilian award in France for his outstanding business successes and decisive contribution to strengthening Indo-French economic ties. President Eisenhower Global Award for Leadership by the Business Council for International Understanding (BCIU) was conferred to him in 2022. Mr. Chandrasekaran is the Co-Chair of the US India CEO Forum. He is on the Board of Governors of New York Academy of Sciences, elected as an international member of the United States National Academy of Engineering (NAE), a member of the UTokyo Global Navigation Board, the Mitsubishi's International Advisory Committee and International Advisory Council of Singapore's Economic Development Board. He is the Chairman of Indian Institute of Management, Lucknow as well as the President of the Court at Indian Institute of Science, Bengaluru. Mr. Chandrasekaran is also a member of the Stanford Doer School for Sustainability Advisory Council and the MIT CEO Advisory Board. Mr. Chandrasekaran is also the author of Bridgital Nation, a groundbreaking book on harnessing technological disruptions to bring Indians closer to their dreams.",
    },
    {
      id: 2,
      name: "MR. P. B. BALAJI",
      designation: "Non Executive (Non Independent) Director",
      img: "/109.webp",
      text: "Mr. P.B. Balaji has been serving as the Group Chief Financial Officer of Tata Motors Limited (\"TML\") since November 2017. He is a member of the Executive Committee of TML and plays a key role in TML Group's profitable and sustainable growth journey. He With nearly three decades of experience in the corporate sector, Mr. Balaji is a seasoned global finance professional who has worked across the FMCG and Automotive industries. He started his career at Unilever in 1995, where he held different corporate finance and supply chain positions in India, Singapore, UK, and Switzerland, Prior to joining Tata Motors, he served as the Chief Financial Officer of Hindustan Unilever. Mr. Balaji holds a post-graduate degree in management from the Indian Institute of Management, Calcutta, and is an alumnus of the Indian Institute of Technology, Chennai.is also on the boards of Jaguar Land Rover, Tata Motors Finance Group, Tata Technologies, and Tata Consumer Products Ltd.",
    },
    {
      id: 3,
      name: "MR. Bharat Puri",
      designation: "Independent Director",
      img: "/110.webp",
      text: "Mr. Bharat Puri is the Non-Executive and Non-Independent Director of Pidilite Industries Limited. Before this, he was the Managing Director of the Company since April 2015, having first joined the Board of Pidilite Industries Ltd as an Independent Director in 2008. With a proven track record as a successful global business leader, he has effectively built, motivated, and directed diverse teams across various regions in both developed and developing markets. He is graduate in Commerce from Punjab University and holds post-graduate diploma in Management (MBA) from IIM, Ahmedabad. Mr. Puri's professional journey began at Asian Paints in 1982, where he started as a Sales & Marketing executive and eventually rose to the position of Head of Sales & Marketing. In 1998, he transitioned to Cadbury India, serving as Director of Sales & Marketing before being appointed as its Managing Director in 2002. Throughout his career, he has held several senior leadership positions in Sales, Marketing, and General Management at both regional and global levels. His last appointment was as the Global President of Chocolates, Gum, and Candy for Mondelez International.",
    },
    {
      id: 4,
      name: "MS. Shikha Sharma",
      designation: "Independent Director",
      img: "/111.webp",
      text: "Ms. Shikha Sharma holds a degree in B.A (Hons.) in Economics, post-graduate diploma in Software Technology from National Center for Software Technology and Post Graduate Diploma in Management from IIM, Ahmedabad. With a wealth of experience in banking and insurance, she boasts an impressive track record. During her tenure, she successfully transformed Axis Bank Limited from a predominantly corporate lender to a bank with a robust retail deposit franchise and a well-balanced lending book. Ms. Sharma embarked on her career with ICICI Bank in 1980. She served as the MD and CEO of ICICI Personal Financial Services from May 1998 to December 2000. Subsequently, she held the position of Managing Director and CEO at ICICI Prudential Life Insurance Company from December 2000 to June 2009. She later became the Managing Director and CEO of Axis Bank from June 2009 to December 2018. Ms. Sharma has earned numerous accolades, including the CNBC TV18 Outstanding Businesswoman of the year, AIMA JRD TATA Corporate Leadership, and Business Standard's Banker of the Year. She has also been recognised as one of the Top 20 Women in Finance-by-Finance Asia and one of the 50 most powerful women in business by Fortune. Ms. Sharma serves on the board of directors for several companies, including Tata Consumer Products Limited, Tech Mahindra Limited, Mahindra & Mahindra Limited, Dr. Reddy's Laboratories Limited, Piramal Enterprises Limited and Mahindra Electric Automobile Limited. Additionally, she is an advisor / consultant to Piramal Enterprises Limited, Billionbrains Garage Ventures Private Limited, Bahaar Foundation – a unit of Akshati Charitable Trust, Google India Digital Services Pvt Ltd and McKinsey & Company Singapore Pte Ltd. She is also a member of the Board of Governors of IIM, Lucknow.",
    },
    {
      id: 5,
      name: "DR. K. P. KRISHNAN",
      designation: "Independent Director",
      img: "/112.webp",
      text: "Dr. K.P. Krishnan retired from the Indian Administrative Service (IAS) on December 31st, 2019, after serving for 37 years. Through his career, he held various positions in the Government of Karnataka, the Government of India, and the World Bank, serving in departments dealing with agriculture, co-operatives, marketing, urban development and infrastructure, commercial taxes, and finance. He also held field positions such as District Collector Mangalore. During his time in the Government of India, he served as Secretary of the Ministry of Skill Development and Entrepreneurship from February 1st, 2017, to December 31st, 2019, as Additional Secretary of the Department of Land Resources, Ministry of Rural Development (2014-2017), Additional Secretary of the Department of Economic Affairs, Ministry of Finance (2013-2014), Secretary of the Prime Minister's Economic Advisory Council (2010-2012), and Joint Secretary of the Department of Economic Affairs, Ministry of Finance (2005-2010). In these roles, he served on the boards of corporations, banks, and statutory regulatory authorities. Dr. Krishnan has also been actively involved in research and academia throughout his government career. He has been a visiting faculty member at various institutions, including IIM Bangalore, ISB, and Ashoka University, and was the Bok Visiting Professor of Regulation at the University of Pennsylvania Law School in 2012-13. He served as the IEPF Chair Professor of Economics at the National Council of Applied Economic Research (NCAER) in New Delhi from August 7th, 2020, to December 31st, 2021, and is currently an Honorary Research Professor at the Centre for Policy Research (CPR) in New Delhi. Dr. Krishnan is also an Independent Director on the Boards of Shriram Capital Private Limited and Dr. Reddy's Laboratories Limited. He studied Economics at St. Stephens College and Law at the Campus Law Centre, University of Delhi, and earned his FPM (Ph.D.) in Economics at IIM Bangalore's 2003 graduation ceremony.",
    },
    {
      id: 6,
      name: "MR. DAVID CREAN",
      designation: "Independent Director",
      img: "/114.webp",
      text: "Mr. David Crean is a highly accomplished and experienced professional in the food industry with over 35 years of expertise in leadership, talent development, innovation, research and development, science, quality management, and food safety. He is graduated with a BA (Hons.) Degree in Applied Biology from Liverpool Polytechnic. He held multiple senior leadership positions at Mars Incorporated, including, when he retired, the dual roles of Vice President of Corporate R&D and Chief Science Officer, where he contributed significantly to the Company's strategy. Throughout his career, he led business growth initiatives, established global technology and research platforms, and most recently established various governance processes and performance standards for Mars' global businesses. He launched over 70 Mars products in multiple geographies and drove profitable business growth across emerging and developed markets. Mr. Crean's passion and leadership have guided Mars' highly principled approach to science, research practices, policies, innovation, quality and food safety standards. Mr. Crean's contributions extend beyond Mars as he participated in many events organised by the United Nations FAO and WHO while advocating for food security and safety. Since he retired from Mars in 2021, he has continued to share his knowledge and expertise, serving as Chair of the Global Food Safety Initiatives (GFSI) Science and Technology Advisory Group and advising numerous global businesses and start-ups.",
    },
    {
      id: 7,
      name: "MR. SUNIL D'SOUZA",
      designation: "Managing Director & CEO",
      img: "/113.webp",
      text: "Mr. Sunil D'Souza has been serving as the Managing Director & Chief Executive Officer of Tata Consumer Products since April 2020. Prior to this, he held the position of Managing Director at Whirlpool India Ltd. for over four years and had a significant contribution in transforming the Whirlpool business in India. He has also worked with PepsiCo for almost 15 years, where he held various leadership positions, managing the commercial aspects of the company's food and beverage portfolio, and steering the business in a large cluster of Asian countries. Mr. D'Souza started his career with Hindustan Unilever in 1993 and has 30 years of extensive experience in the consumer products sector with a strong emphasis on strategy, growth, and execution. In addition to his current role as Managing Director & Chief Executive Officer of the Company, he is also a Director on the Board of Tata Starbucks Limited, Capital Foods Private Limited, NourishCo Beverages Limited, Tata Consumer Soulfull Private Limited, Organic India Private Limited and several of Tata Consumer Products' overseas subsidiaries. Mr. D'Souza holds a degree in engineering from the University of Madras and is an alumnus of the Indian Institute of Management, Calcutta (IIM-C).",
    },
    {
      id: 8,
      name: "MR. AJIT KRISHNAKUMAR",
      designation: "Executive Director & COO",
      img: "/115.webp",
      text: "Mr. Ajit Krishnakumar is Executive Director & Chief Operating Officer of Tata Consumer Products, which he joined in 2020 as Chief Operating Officer. Mr. Krishnakumar joined the Tata Group in 2013 where he worked in the Group Chairman's Office with strategy, corporate finance and M&A responsibilities for the consumer and other business verticals. He also served as the Tata Group nominee on the Boards of Directors of select affiliates. In 2019, he helped lead the Group's effort to consolidate its multiple consumer packaged goods businesses into a single platform, now labelled Tata Consumer Products. At Tata Consumer Products, he oversees business integration & transformation, the integrated India operations as well as the B2B businesses, among other corporate responsibilities. Before he joined the Tata Group, Mr. Krishnakumar was an investment banker and advisor with ~15 years of experience supporting large, medium and small companies think through and execute their strategic, financial and M&A choices. He has worked across a variety of industries and in several countries. He holds an MBA from the University of Michigan, Ann Arbor and a BBA from the University of Hartford, Connecticut.",
    },
  ];
  export default board_leader;
  