const leader_team = [
    {
      id: 9,
      name: "MR. SUNIL D'SOUZA",
      designation: "Managing Director & CEO",
      img: "/leadership/Sunil-Dsouza.webp",
      text: "Mr. Sunil D'Souza has been serving as the Managing Director & Chief Executive Officer of Tata Consumer Products since April 2020. Prior to this, he held the position of Managing Director at Whirlpool India Ltd. for over four years and had a significant contribution in transforming the Whirlpool business in India. He has also worked with PepsiCo for almost 15 years, where he held various leadership positions, managing the commercial aspects of the company's food and beverage portfolio, and steering the business in a large cluster of Asian countries. Mr. D'Souza started his career with Hindustan Unilever in 1993 and has 30 years of extensive experience in the consumer products sector with a strong emphasis on strategy, growth, and execution. In addition to his current role as Managing Director & Chief Executive Officer of the Company, he is also a Director on the Board of Tata Starbucks Limited, Capital Foods Private Limited, NourishCo Beverages Limited, Tata Consumer Soulfull Private Limited, Organic India Private Limited and several of Tata Consumer Products' overseas subsidiaries. Mr. D'Souza holds a degree in engineering from the University of Madras and is an alumnus of the Indian Institute of Management, Calcutta (IIM-C).",
    },
    {
      id: 10,
      name: "MR. AJIT KRISHNAKUMAR",
      designation: "Executive Director & COO",
      img: "/leadership/Ajit-Krishnakumar.webp",
      text: "Mr. Ajit Krishnakumar is Executive Director & Chief Operating Officer of Tata Consumer Products, which he joined in 2020 as Chief Operating Officer. Mr. Krishnakumar joined the Tata Group in 2013 where he worked in the Group Chairman's Office with strategy, corporate finance and M&A responsibilities for the consumer and other business verticals. He also served as the Tata Group nominee on the Boards of Directors of select affiliates. In 2019, he helped lead the Group's effort to consolidate its multiple consumer packaged goods businesses into a single platform, now labelled Tata Consumer Products. At Tata Consumer Products, he oversees business integration & transformation, the integrated India operations as well as the B2B businesses, among other corporate responsibilities. Before he joined the Tata Group, Mr. Krishnakumar was an investment banker and advisor with ~15 years of experience supporting large, medium and small companies think through and execute their strategic, financial and M&A choices. He has worked across a variety of industries and in several countries. He holds an MBA from the University of Michigan, Ann Arbor and a BBA from the University of Hartford, Connecticut.",
    },
    {
      id: 11,
      name: "MR. ASHISH GOENKA",
      designation: "Group Chief Financial Officer",
      img: "/leadership/Ashish-Goenka.webp",
      text: "Mr. Ashish Goenka joined Tata Consumer Products in December 2023 as Group Chief Financial Officer. Mr. Goenka is responsible for the Integrated Finance function overseeing group accounts & finance, investments, capital structuring, forecasting and budgeting and providing strategic direction to businesses whilst developing and delivering annual, mid-term and long-term growth plans for the business. He is also responsible for the legal & compliance, secretarial & governance, investors relations & communications, internal audit & risk management functions of the Company. Mr. Goenka brings more than 20 years of rich experience across the Finance & Strategy function in the FMCG, Telecom & QSR space. He began his career with Hindustan Unilever Limited as a Management Trainee and, in his 14 years with the Company, took on positions of increasing responsibility and complexity, including General Manager Finance, Sales and Customer Development, Strategy Director (South Asia) and Head Finance-Global, Unilever International, Singapore. He, thereafter, joined Bharti Airtel Limited as CFO for Network Services and last served as EVP & Group Finance Controller. He, then, joined Jubilant Foodworks Limited, where he served as President & CFO and led the Finance, Legal and Secretarial function. He is a double gold medalist from IIFT Delhi where he completed his MBA, and is a qualified Chartered Accountant as well as Company Secretary.",
    },
    {
      id: 12,
      name: "MR. TARUN N P VARMA",
      designation: "Global Chief Human Resources Officer",
      img: "/leadership/Tarun-N.-P.Varma.webp",
      text: "Mr. Tarun N P Varma joined Tata Consumer Products (TCP) in January 2023 as Global Chief Human Resources & Sustainability Officer. In this role, he is responsible for developing a competitive and compelling Employee Value Proposition (EVP) for TCP's global organisation besides embedding an integrated people agenda to accelerate delivery across all the pillars of TCP's business strategy. He also provides leadership to the Sustainability team in executing the 'For Better Living' strategy across the 4 Pillars of Planet, Sourcing, Nutrition and Communities. He also holds the office of Chief Ethics Officer for the organisation. Mr. Varma comes with over two decades of experience, having joined Tata Consumer Products from Shell Plc, where he last served as Vice President - HR for the Global Technology division. He earlier led the HR function for Shell Group of Companies in India. Prior to this, he held multiple HR leadership roles across leading multinational corporations such as Vodafone, Coca-Cola, and Nestle. Mr. Varma is a post-graduate in Personnel Management and Industrial Relations from Tata Institute of Social Sciences, Mumbai. He graduated in Mechanical Engineering from National Institute of Technology, Jamshedpur. He is a life member of the National HRD Network and a regular contributor to professional platforms in the field of Human Resources as well as Sustainability.",
    },
    {
      id: 13,
      name: "MR. GHARRY ECCLES",
      designation: "President, International Business",
      img: "/leadership/Gharry-Eccles.webp",
      text: "Mr. Gharry Eccles joined Tata Consumer Products in January 2022 as President - International Business and is based in London. In this role, he is responsible for the business performance of international markets, including the development of a strong portfolio of brands, improved business growth and profitability, driving new products and innovation, and executing on new growth opportunities across markets and regions. With over 3 decades of rich experience in consumer products, Mr. Eccles was previously with Cereal Partners Worldwide– a joint venture between Nestle and General Mills, where he was the Vice President, with business responsibility for the UK, Ireland, Australia and New Zealand covering over 1,000 employees, 3 factories and 2 R&D centres. Prior to this, he held various leadership positions across organisations such as PZ Cussons PLC, Muller Dairy Ltd, The Wrigley Company and Kimberly Clarke, Europe. He is a post-graduate in marketing from Kingston Business School.",
    },
    {
      id: 14,
      name: "MR. RAJESH GOPAL",
      designation: "Global Chief Digital Officer",
      img: "/leadership/Rajesh-Gopal.webp",
      text: "Mr. Rajesh Gopal joined Tata Consumer Products in January 2025 as Global Chief Digital Officer. In this role, Mr. Gopal is responsible for building on organizational capabilities and further propelling the organization's digital agenda. Mr. Gopal has over 22 years of experience in leading digital strategy and driving large scale technology transformation initiatives. Prior to joining Tata Consumer Products, he was the Regional Chief Information Officer – APAC and GCC Head at Kimberly-Clark. He has earlier held leadership positions in the Digital function at ITC Limited, L'Oreal and Unilever. Mr. Gopal holds a Master's degree in Industrial engineering from the Georgia Institute of Technology, USA, and a Bachelor's degree in Mechanical engineering from Annamalai University, India.",
    },
    {
      id: 15,
      name: "MR. VIKAS GUPTA",
      designation: "Global Head, R&D",
      img: "/leadership/Vikas-Gupta.webp",
      text: "Mr. Vikas Gupta was appointed the Global Head of R&D for Tata Consumer Products in June 2020. He began as the Head of Product Innovation for India in 2013 and was appointed the Head of Global NPD in 2017 for the Beverages business. Mr. Gupta has played a key role in achieving successful launches of innovation projects for the tea and coffee category globally. Mr. Gupta brings diverse experience of the Food and Beverages industry with demonstrated leadership capabilities in new product development, cost innovation and supply chain to develop and launch innovation projects. Previously, he spent almost a decade in GlaxoSmithKline Consumer Healthcare Limited across R&D and Supply Chain functions and 3 years with Hindustan Unilever Ltd. in the R&D function. Mr. Gupta has a master's in Food Technology from the Central Food Technology Research Institute, Mysore and is a graduate in Horticulture from University of Horticulture and Forestry, Solan, Himachal Pradesh.",
    },
    {
      id: 16,
      name: "MR. PUNEET DAS",
      designation: "President, Packaged Beverages India and South Asia",
      img: "/leadership/Puneet-Das.webp",
      text: "Mr. Puneet Das joined Tata Consumer Products in November 2017. He was appointed President – Packaged Beverages (India and South Asia) in April 2021. Prior to this, he was Senior Vice President – Packaged Beverages, India where he played a key role in strengthening the core Tata Tea brand and sub-brands. He currently drives growth strategy, business outcomes, and P&L for the Packaged Beverages category (Tata Tea, Tetley, Tata Coffee) including new growth business of Organic India. Mr. Das has a rich experience in the FMCG industry in India as well as international markets such as the Sub-Saharan African region, Bangladesh, Nepal, Myanmar and Sri Lanka. He has held senior marketing positions in Marico, Pepsico, GSK Consumer and has worked on iconic brands such as 7Up, Boost and Horlicks, among others. A respected marketer and award winner, Mr. Das has won the CMO leadership award in 2025 and been recognised as CMO leader 'Marketer of the Year 2020' by Brand Equity.com, Pitch 'Best CMO award' for excellence in purpose-driven marketing (2020 and 2019) and is among the Super 30 CMO Honour Roll 2020 for the trailblazing work in marketing the Tata Tea portfolio. Mr. Das is a graduate from St. Stephen's College, Delhi, and holds a postgraduate diploma in management (MBA) from XLRI, Jamshedpur.",
    },
    {
      id: 17,
      name: "MS. DEEPIKA BHAN",
      designation: "MS. DEEPIKA BHAN President, Packaged Foods (India)",
      img: "/leadership/Deepika-Bhan.webp",
      text: "Ms. Deepika Bhan joined Tata Consumer Products in May 2021, as President - Foods Business. Prior to this, she spent 15 years at Hindustan Unilever Ltd., most recently as the Global Brand Director where she led the brand development, innovation and communication agenda for the Hair Care portfolio for South Asia. Having worked on leadership assignments across Sales and Marketing, Ms. Bhan brings her rich experience and expertise in brand crafting and communication, driving innovation, building new categories and P&L management combined with a strong understanding of frontline sales. She is particularly passionate about building brands and business with purpose at its heart. Ms. Bhan is an Economics (Hons.) graduate from St. Xavier's' College and holds a master's degree in business administration from Xavier Institute of Management, Bhubaneswar, Odisha.",
    },
    {
      id: 18,
      name: "MR. PARTHA BISWAS",
      designation: "President – Ready-To-Drink (RTD) Business",
      img: "/leadership/Partha-Biswas.webp",
      text: "Mr. Partha Biswas joined Tata Consumer Products in October 2024 as President – Ready-To-Drink (RTD) Business. Prior to this, he was Executive Vice President and Head of Viacom 18's largest entertainment channel. He was also the Chief Operating Officer at ACT Fibernet. He has earlier held significant roles spanning category development, operations and general management at Hindustan Coca- Cola Beverages. Mr. Biswas brings 20 years of experience spanning category leadership, business strategy and sales and marketing. Mr. Biswas is a graduate from Malaviya National Institute of Technology, Jaipur, and holds a postgraduate degree in Management (MBA) in Marketing & Operations from Faculty of Management Studies, University of Delhi. He also graduated as an Alfred P. Sloan Fellow from the MIT Sloan School of Management.",
    },
    {
      id: 19,
      name: "MR. PRASHANT PARAMESWARAN",
      designation: "Managing Director & CEO, Tata Consumer Soulfull Pvt. Ltd.",
      img: "/leadership/Prashant-Parameswaran.webp",
      text: "Mr. Prashant Parameswaran is the MD and CEO of Tata Consumer Soulfull Private Ltd since April 2021. In his previous role, he served as the Co-Founder and MD/CEO of Kottaram Agro Foods (Soulfull) for ten years. Under the brand name 'Soulfull', he brought back traditional grains like millets to the modern Indian consumer in a form that is relevant for the 21st century. With over 20 years of experience, Mr. Parameswaran began his career in 2001 by successfully setting up the distribution, operations and retail business units in India for the Kottaram Group. He has also worked in the USA with international firms such as Limited Brands and Information Resources Inc., as a Director supporting the Marketing Strategies team at Safeway Supermarkets from their headquarters in California. He led the team in managing revenues and acquiring new business opportunities. Mr. Parameswaran is an engineering graduate from PSG College of Technology, Tamil Nadu and holds an MBA from Babson College – Franklin W. Olin Graduate School of Business. He is a Member of the Young Presidents Organisation (YPO), Bangalore Chapter and was an active Round Tabler in Bengaluru and Cochin until 2020.",
    },
    {
      id: 20,
      name: "MR. PUNIT GUPTA",
      designation: "President & Head - India Sales",
      img: "/leadership/Punit-Gupta.webp",
      text: "Mr. Punit Gupta joined Tata Consumer Products in April 2021, and currently leads the Sales function for India business. Prior to heading sales, he was heading Strategy and M&A, where he drove multiple strategy engagements and led marquee acquisitions for Tata Consumer Products. He has over 19 years of experience across operational and consulting roles, including leading and delivering large-scale, complex transformation engagements across India, APAC, Europe and North America. Prior to Tata Consumer, Mr. Gupta headed business strategy for Samsung Electronics for South-West Asia driving strategic initiatives for the smartphone and the consumer durables businesses. He started his career in operational roles with Asian Paints and Hindustan Unilever Ltd., where he managed large sales teams across India, spanning more than 40 FMCG product categories, like decorative paints, home and personal care and foods & beverages. During his strategy consulting assignments with Accenture and A.T. Kearney, he led 30+ CXO level engagements with cross-functional teams across the globe.",
    },
    {
      id: 21,
      name: "MR. RISHI GAUTAM",
      designation: "Global General Counsel",
      img: "/leadership/Rishi-Gautam.webp",
      text: "Mr. Rishi Gautam is the Global General Counsel and in-charge of the legal function for Tata Consumer Products and its worldwide operations, grouped under India, CAA and EMEA regions. He is based in Mumbai and is a member of the Executive Committee. As the Global General Counsel, Mr. Gautam is responsible for legal affairs and strategy, including operational legal matters, restructuring, reorganisation, acquisitions and joint ventures. In his previous role, he served as a partner with leading Indian law firms (Cyril Amarchand Mangaldas and AZB & Partners). Previously, he has worked with leading international law firms (Clifford Chance and Herbert Smith Freehills). Mr. Gautam commenced practice of law as an Advocate (India) in 2001 and has over 23 years of extensive global experience, having worked in regions, such as United Kingdom and Australia. He is also registered as a Solicitor (England & Wales). Mr. Gautam holds a Bachelor of Arts and Bachelor of Law (BA LLB) (Hons.) degree from National Law School of India University with a Gold Medal (Constitutional Law). He is an awardee of the National Talent Search Scholarship by the Government of India.",
    },
    {
      id: 22,
      name: "MR. ABHIJIT MIDHA",
      designation: "Senior Vice President - Strategy& M&A",
      img: "/leadership/Abhijit-Midha.webp",
      text: "Mr. Abhijit Midha, is serving as the Senior Vice President - Strategy and M&A of the Company w.e.f. December 27, 2023. Prior to joining Tata Consumer Products Limited, Mr. Midha was a Senior Vice President – Key Accounts with Zomato Ltd. Mr. Midha has worked for 17.5 years across organisations including McKinsey & Company, Citigroup Venture Capital International (CVCI), CK Birla Group and Premji Invest. Mr. Midha comes in with extensive experience in Private Equity, Strategy, M&A, Business Transformation and Value Creation in sectors such as Consumer Goods, Retail, Healthcare and Financial Services. Mr. Midha graduated from IIT Delhi in 2004 where he secured the Institute Silver Medal, and is an alumnus of IIM Ahmedabad, batch of 2006.",
    },
    {
      id: 22,
      name: "MR. AMIT PANT",
      designation: "Senior Vice President & Head - Solubles Business",
      img: "/leadership/Amit-Pant.webp",
      text: "Mr. Amit Pant heads Solubles – the B2B arm of Tata Consumer Products Limited. He joined Tata Coffee in 2014 where he headed the Sales & Marketing function of the organization. During his stint in Tata Coffee, he was instrumental in significantly scaling up the size of instant coffee business including successful commercialization of Vietnam operations. Prior to that, he spent 9 years with Olam where he was manging the Indian operations as a part of the global Coffee and Dairy product divisions. Before Olam, he worked with Godrej Agrovet for 5 years and ITW Signode for 6 years. In a career spanning 30 years his professional experience has largely centred around international trade, B2B client handling, soft commodities, risk management and running profit centres. He is an engineer by training and a PGDM (Specialization in Agriculture) from IIM Ahmedabad.",
    },
  ];
  export default leader_team;